version: "3.4"

services:
################################################################################
# All of the infrastructure services
################################################################################
  mongodb:
    image: mongo:6
    container_name: cdp-infra-mongodb
    network_mode: "host"
    ports:
      - 27017:27017
    volumes:
      - cdp-infra-mongodb-data:/data
    restart: always

################################################################################
  localstack:
    image: localstack/localstack:3.0
    container_name: cdp-infra-localstack
    network_mode: "host"
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    restart: always
    environment:
      - LOCALSTACK_HOST=127.0.0.1
      - SERVICES=s3,sqs,sns
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3

################################################################################
  redis:
    image: redis:7.0-alpine
    network_mode: "host"
    container_name: cdp-infra-redis
    ports:
      - 6379:6379
    restart: always

################################################################################
  selenium-chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    network_mode: "host"

################################################################################
  cdp-mock-oidc:
    image: defradigital/cdp-mock-oidc
    container_name: cdp-mock-oidc
    network_mode: "host"
      
################################################################################
# Portal Init script
################################################################################
  setup-cdp-portal:
    image: defradigital/cdp-local-setup:latest
    network_mode: "host"
    env_file:
      - ./config/local-defaults.env
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./scripts/portal:/scripts:ro
    restart: "no"
    profiles:
      - portal

################################################################################
  cdp-portal-frontend:
    image: defradigital/cdp-portal-frontend:${CDP_PORTAL_FRONTEND:-latest}
    container_name: cdp-portal-frontend
    network_mode: "host"
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-portal-frontend.env
    environment:
      - PORT=3000
    depends_on:
      setup-cdp-portal:
        condition: service_completed_successfully
    profiles:
      - portal

################################################################################
  cdp-user-service-backend:
    image: defradigital/cdp-user-service-backend:${CDP_USER_SERVICE_BACKEND:-latest}
    container_name: cdp-user-service-backend
    network_mode: "host"
    ports:
      - 3002:3002
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-user-service-backend.env
    environment:
      - PORT=3001
    depends_on:
      setup-cdp-portal:
        condition: service_completed_successfully
    profiles:
      - portal

################################################################################
  cdp-portal-backend:
    image: defradigital/cdp-portal-backend:${CDP_PORTAL_BACKEND:-latest}
    container_name: cdp-portal-backend
    network_mode: "host"
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-portal-backend.env
    environment:
      - ASPNETCORE_URLS=http://+:5094
    depends_on:
      setup-cdp-portal:
        condition: service_completed_successfully
      cdp-user-service-backend:
        condition: service_started
    profiles:
      - portal

################################################################################
  cdp-self-service-ops:
    image: defradigital/cdp-self-service-ops:${CDP_SELF_SERVICE_OPS:-latest}
    container_name: cdp-self-service-ops
    network_mode: "host"
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-self-service-ops.env
    depends_on:
      setup-cdp-portal:
        condition: service_completed_successfully
    environment:
      - PORT=3009
    profiles:
      - portal

################################################################################
  cdp-portal-stubs:
    image: defradigital/cdp-portal-stubs:${CDP_PORTAL_STUBS:-latest}
    container_name: cdp-portal-stubs
    network_mode: "host"
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-portal-stubs.env
    environment:
      - PORT=3939
    profiles:
      - portal

################################################################################

volumes:
  cdp-infra-mongodb-data:
