version: "3.4"

services:
################################################################################
# All of the infrastructure services
################################################################################
  proxy:
    image: nginxproxy/nginx-proxy:1.4
    container_name: cdp-proxy
    ports:
      - "3333:80"
    environment:
      - ENABLE_IPV6=true
      - DEFAULT_ROOT="418"
      - DEFAULT_HOST=~^cdp\..*\.sslip\.io
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/cdp-proxy.conf:/etc/nginx/conf.d/cdp-proxy.conf:ro
    networks:
      - cdpnet

################################################################################
  mongodb:
    image: mongo:6.0.13
    container_name: cdp-infra-mongodb
    networks:
      - cdpnet
    ports:
      - 27017:27017
    volumes:
      - cdp-infra-mongodb-data:/data
    restart: always

################################################################################
  localstack:
    image: localstack/localstack:3.0.2
    container_name: cdp-infra-localstack
    networks:
      - cdpnet
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    restart: always
    environment:
      - LOCALSTACK_HOST=127.0.0.1
      - SERVICES=s3,sqs,sns
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3

################################################################################
  redis:
    image: redis:7.2.3-alpine3.18
    networks:
      - cdpnet
    container_name: cdp-infra-redis
    ports:
      - 6379:6379
    restart: always

################################################################################
  selenium-chrome:
    image: selenium/standalone-chrome:119.0
    container_name: selenium-chrome
    networks:
      - cdpnet
    ports:
      - 4444:4444
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "cdp.127.0.0.1.sslip.io:host-gateway"
      - "cdp.--1.sslip.io:host-gateway"

################################################################################
# Portal Init script
################################################################################
  setup-cdp-portal:
    image: defradigital/cdp-local-setup:latest
    networks:
      - cdpnet
    env_file:
      - ./config/local-defaults.env
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./scripts/portal:/scripts:ro
    restart: "no"

################################################################################
  cdp-portal-frontend:
    image: defradigital/cdp-portal-frontend:${CDP_PORTAL_FRONTEND:-latest}
    container_name: cdp-portal-frontend
    networks:
      - cdpnet
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "cdp.127.0.0.1.sslip.io:host-gateway"
      - "cdp.--1.sslip.io:host-gateway"
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-portal-frontend.env
    environment:
      - VIRTUAL_HOST=~^cdp\..*\.sslip\.io
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=3000
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      cdp-portal-backend:
        condition: service_started
      cdp-user-service-backend:
        condition: service_healthy
      cdp-portal-stubs:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "echo", "Y29uc3QgZT1yZXF1aXJlKCJodHRwIiksdD17aG9zdG5hbWU6ImxvY2FsaG9zdCIscG9ydDpwcm9jZXNzLmVudi5QT1JULHBhdGg6Ii9oZWFsdGgiLG1ldGhvZDoiR0VUIn0sbz1lLnJlcXVlc3QodCwoZT0+e2xldCB0PSIiO2Uub24oImRhdGEiLChlPT57dCs9ZX0pKSxlLm9uKCJlbmQiLCgoKT0+e3Byb2Nlc3MuZXhpdCgwKX0pKX0pKTtvLm9uKCJlcnJvciIsKGU9Pntwcm9jZXNzLmV4aXQoMSl9KSksby5lbmQoKTsK", "|", "base64", "-d", "|", "node", "-"]
      interval: 3s
      start_period: 2s
      retries: 3
    profiles:
      - portal

################################################################################
  cdp-user-service-backend:
    image: defradigital/cdp-user-service-backend:${CDP_USER_SERVICE_BACKEND:-latest}
    container_name: cdp-user-service-backend
    networks:
      - cdpnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "cdp.127.0.0.1.sslip.io:host-gateway"
      - "cdp.--1.sslip.io:host-gateway"
    ports:
      - 3001:3001
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-user-service-backend.env
    environment:
      - PORT=3001
    depends_on:
      cdp-portal-stubs:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "echo", "Y29uc3QgZT1yZXF1aXJlKCJodHRwIiksdD17aG9zdG5hbWU6ImxvY2FsaG9zdCIscG9ydDpwcm9jZXNzLmVudi5QT1JULHBhdGg6Ii9oZWFsdGgiLG1ldGhvZDoiR0VUIn0sbz1lLnJlcXVlc3QodCwoZT0+e2xldCB0PSIiO2Uub24oImRhdGEiLChlPT57dCs9ZX0pKSxlLm9uKCJlbmQiLCgoKT0+e3Byb2Nlc3MuZXhpdCgwKX0pKX0pKTtvLm9uKCJlcnJvciIsKGU9Pntwcm9jZXNzLmV4aXQoMSl9KSksby5lbmQoKTsK", "|", "base64", "-d", "|", "node", "-"]
      interval: 3s
      start_period: 2s

    profiles:
      - portal

################################################################################
  cdp-portal-backend:
    image: defradigital/cdp-portal-backend:${CDP_PORTAL_BACKEND:-latest}
    container_name: cdp-portal-backend
    networks:
      - cdpnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "cdp.127.0.0.1.sslip.io:host-gateway"
      - "cdp.--1.sslip.io:host-gateway"
    ports:
      - 5094:5094
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-portal-backend.env
    environment:
      - ASPNETCORE_URLS=http://+:5094
    depends_on:
      setup-cdp-portal:
        condition: service_completed_successfully
      cdp-user-service-backend:
        condition: service_healthy
    profiles:
      - portal

################################################################################
  cdp-self-service-ops:
    image: defradigital/cdp-self-service-ops:${CDP_SELF_SERVICE_OPS:-latest}
    container_name: cdp-self-service-ops
    networks:
      - cdpnet
    ports:
      - 3009:3009
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "cdp.127.0.0.1.sslip.io:host-gateway"
      - "cdp.--1.sslip.io:host-gateway"
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-self-service-ops.env
    depends_on:
      cdp-portal-stubs:
        condition: service_healthy
    environment:
      - PORT=3009
    healthcheck:
      test: ["CMD", "echo", "Y29uc3QgZT1yZXF1aXJlKCJodHRwIiksdD17aG9zdG5hbWU6ImxvY2FsaG9zdCIscG9ydDpwcm9jZXNzLmVudi5QT1JULHBhdGg6Ii9oZWFsdGgiLG1ldGhvZDoiR0VUIn0sbz1lLnJlcXVlc3QodCwoZT0+e2xldCB0PSIiO2Uub24oImRhdGEiLChlPT57dCs9ZX0pKSxlLm9uKCJlbmQiLCgoKT0+e3Byb2Nlc3MuZXhpdCgwKX0pKX0pKTtvLm9uKCJlcnJvciIsKGU9Pntwcm9jZXNzLmV4aXQoMSl9KSksby5lbmQoKTsK", "|", "base64", "-d", "|", "node", "-"]
      interval: 3s
      start_period: 2s
    profiles:
      - portal

################################################################################
  cdp-portal-stubs:
    image: defradigital/cdp-portal-stubs:${CDP_PORTAL_STUBS:-latest}
    container_name: cdp-portal-stubs
    networks:
      - cdpnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "cdp.127.0.0.1.sslip.io:host-gateway"
      - "cdp.--1.sslip.io:host-gateway"
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-portal-stubs.env
    ports:
      - 3939:3939
    environment:
      - PORT=3939
    depends_on:
      setup-cdp-portal:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "echo", "Y29uc3QgZT1yZXF1aXJlKCJodHRwIiksdD17aG9zdG5hbWU6ImxvY2FsaG9zdCIscG9ydDpwcm9jZXNzLmVudi5QT1JULHBhdGg6Ii9oZWFsdGgiLG1ldGhvZDoiR0VUIn0sbz1lLnJlcXVlc3QodCwoZT0+e2xldCB0PSIiO2Uub24oImRhdGEiLChlPT57dCs9ZX0pKSxlLm9uKCJlbmQiLCgoKT0+e3Byb2Nlc3MuZXhpdCgwKX0pKX0pKTtvLm9uKCJlcnJvciIsKGU9Pntwcm9jZXNzLmV4aXQoMSl9KSksby5lbmQoKTsK", "|", "base64", "-d", "|", "node", "-"]
      interval: 3s
      start_period: 2s
    profiles:
      - portal

################################################################################

volumes:
  cdp-infra-mongodb-data:

networks:
  cdpnet:
    driver: bridge
