version: "3.4"

services:
################################################################################
# All of the infrastructure services
################################################################################
  cdp-infra-mongodb:
    image: mongo:6
    container_name: cdp-infra-mongodb
    ports:
      - 27017:27017
    volumes:
      - cdp-infra-mongodb-data:/data
    restart: always

################################################################################
  cdp-infra-localstack:
    image: localstack/localstack:3.0
    container_name: cdp-infra-localstack
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    restart: always
    environment:
      - LOCALSTACK_HOST=cdp-infra-localstack
      - SERVICES=s3,sqs,sns
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3

################################################################################
  cdp-infra-redis:
    image: redis:7.0-alpine
    container_name: cdp-infra-redis
    ports:
      - 6379:6379
    restart: always

################################################################################
  selenium-chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    ports:
      - 4444:4444
   

################################################################################
  cdp-mock-oidc:
    image: defradigital/cdp-mock-oidc
    container_name: cdp-mock-oidc
    ports:
      - 5557:5557
    command: ["/app/oidc-server", "start", "-c", "config.yaml","--listen-addr", "cdp-mock-oidc"]
      
################################################################################
# Portal Init script
################################################################################
  setup-cdp-portal:
    image: defradigital/cdp-local-setup:latest
    env_file:
      - ./config/local-defaults.env
    depends_on:
      cdp-infra-localstack:
        condition: service_healthy
      cdp-infra-mongodb:
        condition: service_started
      cdp-infra-redis:
        condition: service_started
    volumes:
      - ./scripts/portal:/scripts:ro
    restart: "no"
    profiles:
      - portal

################################################################################
  cdp-portal-frontend:
    image: defradigital/cdp-portal-frontend:${CDP_PORTAL_FRONTEND:-latest}
    container_name: cdp-portal-frontend
    
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-portal-frontend.env
    ports:
      - 3000:80
    depends_on:
      setup-cdp-portal:
        condition: service_completed_successfully
    profiles:
      - portal

################################################################################
  cdp-user-service-backend:
    image: defradigital/cdp-user-service-backend:${CDP_USER_SERVICE_BACKEND:-latest}
    container_name: cdp-user-service-backend
    ports:
      - 3002:80
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-user-service-backend.env
    depends_on:
      setup-cdp-portal:
        condition: service_completed_successfully
    profiles:
      - portal

################################################################################
  cdp-portal-backend:
    image: defradigital/cdp-portal-backend:${CDP_PORTAL_BACKEND:-latest}
    container_name: cdp-portal-backend
    ports:
      - 5094:80
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-portal-backend.env
    depends_on:
      setup-cdp-portal:
        condition: service_completed_successfully
      cdp-user-service-backend:
        condition: service_started
    profiles:
      - portal

################################################################################
  cdp-self-service-ops:
    image: defradigital/cdp-self-service-ops:${CDP_SELF_SERVICE_OPS:-latest}
    container_name: cdp-self-service-ops
    ports:
      - 3009:80    
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-self-service-ops.env
    depends_on:
      setup-cdp-portal:
        condition: service_completed_successfully
    profiles:
      - portal

################################################################################
  cdp-portal-stubs:
    image: defradigital/cdp-portal-stubs:${CDP_PORTAL_STUBS:-latest}
    container_name: cdp-portal-stubs
    ports:
      - 3939:80    
    env_file:
      - ./config/local-defaults.env
      - ./config/cdp-portal-stubs.env
    profiles:
      - portal

################################################################################

volumes:
  cdp-infra-mongodb-data:
